definitions:
  vo.GetContentResponse:
    properties:
      created:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Rest API server written by GO
  version: "1.0"
paths:
  /create:
    post:
      consumes:
      - application/json
      description: file로 binary 파일을 받고, name이 있을 경우 name을 파일명으로, 없을 경우 file의 file명을
        테이블에 저장한다.
      parameters:
      - description: content file (100MB 초과 불가)
        in: formData
        name: file
        required: true
        type: file
      - description: 파일명
        in: formData
        name: name
        type: string
      produces:
      - application/json
      responses: {}
      summary: 파일을 기반으로 레코드를 생성한다.
  /delete/{id}:
    delete:
      consumes:
      - application/json
      description: 삭제한다.
      parameters:
      - description: content Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: path id로 레코드를 삭제한다.
  /read/{id}:
    get:
      consumes:
      - application/json
      description: 아이디, 파일명, 생성일시를 제공한다
      parameters:
      - description: content Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.GetContentResponse'
      summary: path id로 데이터를 조회
  /read/{id}/file:
    get:
      consumes:
      - application/json
      description: id의 content를 파일로 다운로드 한다.
      parameters:
      - description: content Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.GetContentResponse'
      summary: path id로 파일 조회
  /update/{id}:
    put:
      consumes:
      - application/json
      description: 파일과 name을 수정한다.
      parameters:
      - description: content Id
        in: path
        name: id
        required: true
        type: integer
      - description: content file
        in: formData
        name: file
        required: true
        type: file
      - description: 파일명
        in: formData
        name: name
        type: string
      produces:
      - application/json
      responses: {}
      summary: path id로 수정한다.
swagger: "2.0"
